import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from matplotlib import pyplot as plt
import random
import numpy as np
import torch
from learning.trainer import Trainer

# Centralized hyperparameters for both training and evaluation runs.
hyperparams = {
    "discount_factor": 0.99,
    "batch_size": 100,
    "memory_capacity": 10000,
    "max_episodes": 600,
    "goal": 200,
    "network_size": 20,
    "epsilon_max": 1.0,
    "epsilon_min": 0.01,
    "epsilon_decay": 0.00005,
}

# Set True to train from scratch, False to evaluate a saved model.
train_mode = True


if __name__ == "__main__":

    if train_mode:
        # Keep one explicit seed for reproducibility of this run.
        seed = 49
        rewards_list = {}
        loss_list = {}
        print(f"Training with seed: {seed}")
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
        trainer = Trainer(hyperparams, seed)
        rewards, loss = trainer.train()
        rewards_list[seed] = rewards
        loss_list[seed] = loss
        reward_runs = list(rewards_list.values())
        mean_rewards = np.mean(reward_runs, axis=0)
        std_rewards = np.std(reward_runs, axis=0)

        # Plot episode rewards for quick visual sanity check.
        plt.figure(figsize=(10,6))
        plt.plot(rewards, label=f"Seed {seed}",color="black", linewidth=2,  alpha=0.6)
        plt.xlabel("Episode", fontsize=14)
        plt.ylabel("Reward", fontsize=14)
        plt.title("Training Cartpole with RMSProp", fontsize=16)
        plt.legend()
        plt.grid(True)
        plt.show()

    else:
        # Expects model generated by training mode
        trainer = Trainer(hyperparams, seed=None)
        trainer.test("best_model_seed_49.pth")